#!/bin/sh

# fast way to open often visited pages just edit pages.txt
# works with surf and firefox, if no option is passed to fmarks, it assumes surf

#--------------------------------------------------------------------------------
# files
#--------------------------------------------------------------------------------

PAGES=$HOME/repos/bookmarks/pages.txt

#-------------------------------------------------------------------------------

usage () {
    echo "Usage: $0 [-h] [-f]"
}

fflag=0
sflag=0

while :
do
    case $1 in
	-h)
	    usage
	    exit 0
	    ;;
	-f)
	    fflag=1
	    break
	    ;;
	*)
	    if [ $# -eq 0 ]; then
		sflag=1
		break;
	    else
		usage
		exit 1
	    fi
	    ;;
    esac
done

if [ $sflag -eq 1 ]; then
    URL=$(dmenu -l 10 < "$PAGES")
    if [ -n "$URL" ]; then
	surf -sg "$URL" &
    fi
fi

if [ $fflag -eq 1 ]; then
    URL=$(dmenu -l 10 < "$PAGES")
    if [ -n "$URL" ]; then
	firefox -new-tab "$URL" 2>/dev/null
    fi
fi
