#!/bin/sh

#-------------------------------------------------------------------------------
# files
#-------------------------------------------------------------------------------

BROWSER=firefox
#BROWSER=surf
BOOKMARKS=$HOME/repos/bookmarks/bookmarks.txt
TMPBOOKMARKS=$HOME/repos/foxy/tmp.txt

#-------------------------------------------------------------------------------
# functions
#-------------------------------------------------------------------------------
usage () {
    echo "Usage: $0 [-h] [-t] [-s tag] [-a link @tag1 @tag2...@tagn]"
}

tag_array () {
    tagz=""
    
    for i in $args
    do
	if [ $i == "-a" ]; then
	    continue
	elif [ $i == "-s" -o $i == "-t" ]; then
            echo "don't use more than one flags"
            usage
            exit 1
	else
		tagz+=$i
		tagz+=" "
	fi
    done
    # keep only the tags
    tagz=$(echo $tagz | awk -F': ' '{print $1}' | sed -n 's/[^@]*//p')
    # append ": " to the and of the tags and the link
    echo $tagz | sed 's/$/: /' | sed "s%$%$dalink%" >> $BOOKMARKS
    # append new line to the end of the bookmark file
    echo '' >> $BOOKMARKS
exit 0
}

show_bmarks () {
    cat $BOOKMARKS | grep $tag | awk -F': ' '{print $2}' > $TMPBOOKMARKS
    URL=$(cat $TMPBOOKMARKS | dmenu -l 10)
    if [ -n "$URL" ]; then
        if [ "$BROWSER" = "firefox" ]; then
	    $BROWSER -new-tab $URL 2>/dev/null
        else
            $BROWSER -isg $URL &
        fi
    else
	echo "no links found"
    fi	
}

show_tags () {
    cat $BOOKMARKS | awk '{print $0}' RS=' ' | grep @ | sed 's/://' | sort -u | dmenu -l 10
}

#-------------------------------------------------------------------------------
# argument parsing
#-------------------------------------------------------------------------------

aflag=0
sflag=0
tflag=0

while :
do
    case $1 in
	-h)
	    usage
	    exit 0
	    ;;
	-s)
	    nargs=$#
	    sflag=1
	    tag=$2
	    tag=$(echo $tag | sed 's/^/@/')
	    break
	    ;;
	-a)
	    nargs=$#
	    args=$*
	    dalink=$2
	    aflag=1
	    break
	    ;;
	-t)
	    nargs=$#
	    tflag=1
	    break
	    ;;
	*)
	    usage
	    exit 1
	    ;;
    esac
done
#-------------------------------------------------------------------------------

if [ $sflag -eq 1 -a $nargs -lt 3 -a $tflag -eq 0 ]; then
    show_bmarks $tag
    exit 0
elif [ $aflag -eq 1 -a $nargs -gt 2 ]; then
    tag_array $args $dalink
    exit 0
elif [ $tflag -eq 1 -a $nargs -eq 1 ]; then
    show_tags
    exit 0
else
    echo 'not enough or too many params'
    usage
    exit 1
fi
